### ISSUE TITLE
v0.11.0 Refactor, v1.0.0-rc.1 release

### ISSUE THREAD

**Issue by citycide** [citycide/trilogy#14]
**Update 1-9-17**: the new version has been pushed to npm as `@next`. Give it a shot and throw me any feedback you might have. Docs are currently available as `.md` files in the `next` branch here in the repo.

### the future of trilogy

I'm looking to make some sweeping changes to trilogy. Most of the codebase will be rewritten to be simpler, and the API is going to change almost entirely. It'll first be published as the `@next` tag to NPM before eventually becoming the latest release.

When the v0.11.x series is considered whatever you want 'ready' to mean ( :joy: ), it will be released as v1.0.0-rc.1. Then, barring any blocking issues it'll be pushed to v1.0.0 and considered stable. :cake: Otherwise we'll ride that rc car until the batteries die... then we'll recharge them.

### the past of trilogy

Let's back up a bit for a sec - trilogy started as a personal project, and really was a small module in a larger app that just layered over `sql.js` so I could stop using raw query strings. I also have grown away from chainable APIs of late, so `knex` by itself did not solve all my problems. Chains have their uses but I was looking for something different for my database.

I liked the idea of document stores that take after Mongo, like [nedb](https://github.com/louischatriot/nedb) and [linvodb](https://github.com/Ivshti/linvodb3), but SQLite is generally faster and then there's the whole relational vs non-relational debate and so on. Long story short I wanted to stick to SQLite, but I admired the APIs of these other options.

That's why trilogy's API doesn't really feel like SQL. In the project for which trilogy was originally built, I expose the database over a plugin architecture. I felt knex's chaining would become a pain for plugin authors so I chased a simpler API similar to document stores.

### fast forward

Alright so we're here at v0.10.0. There are probably a couple people using trilogy, or at least a few interested based on the repo stars.

With version 0.11.0, the API will undergo major changes. Where currently you would use code that looks like this:

```javascript
db.createTable('people', {
  id: { type: 'integer', primary: true },
  name: { type: 'text' },
  power_level: { type: 'integer' }
}).then(() => {
  return db.insert('people', {
    id: 456789,
    name: 'citycide',
    power_level: 9001
  })
}).then(() => {
  return db.select('people', 'name', ['power_level', '>', 9000])
}).then(names => {
  console.log(names)
  // -> [{ name: 'citycide' }]
})
```

... you'd use this instead:

```javascript
db.model('people', {
  id: { type: Number, primary: true },
  name: String,
  power_level: Number
}).then(people => {
  // could also be `db.create('people', { ... })`
  return people.create({
    id: 456789,
    name: 'citycide',
    power_level: 9001
  })
}).then(() => {
  // could also be `db.find('people.name', ['power_level', '>', 9000])`
  return people.find('name', ['power_level', '>', 9000])
}).then(names => {
  console.log(names)
  // -> ['citycide']
})
```

So the general idea remains the same but trilogy will now use `model`s to keep track of the schema of your tables based on the types you specify. When you insert or retrieve data, the types will be cast as necessary to fit this schema so that you always receive what you expect to receive.

The model architecture also allows for a couple different ways to use the API. You could just always use `db.find('people.name', { ... })`, or you could use `people.find('name', { ... })` - `db.model()` returns that model instance.

I also hope to **bring support for the native `sqlite3` module** along with `sql.js`.

**Update**: ^ `sqlite3` is now supported in addition to `sql.js`! :tada: If you update and would like to continue using `sql.js`, supply it as `options.client` in the constructor options as the default is now `sqlite3` for performance & asynchronous reasons.

### API map from old to new

These are the methods I've been able to mostly hash out, and how they relate to the current version of trilogy:

| v0.10.0 | v0.11.0 |
|-------------------|---------------------|
| `createTable()` | `model()` |
| `decrement()` | `decr()` |
| `del()` | `remove()` & `clear()` |
| `dropTable()` | `dropModel()` |
| `first()` | `findOne()` |
| `getValue()` | `get()` |
| `hasTable()` | `hasModel` |
| `increment()` | `incr()` |
| `insert()` | `create()` |
| `select()` | `find()` |
| `update()` | `update()` + `set()` (`get()` equivalent) |
| `queryBuilder` | `knex` |

Also, instead of using an options object like `{ conflict: 'replace' }` with `insert()`, there are new methods `findOrCreate()` and `updateOrCreate()`.

| new methods |
|----------------|
| `min()` |
| `max()` |
| `findOrCreate()` |
| `updateOrCreate()` |

| removed | reason |
|-----------|---------|
| `coercion` | models coerce values as needed, user specifies types |
| `schemaBuilder` | creating tables outside trilogy doesn't allow trilogy to handle the types; technically still available as `knex.schema` however |

| signature changes only |
|--------------------------|
| `count()` |
| `raw()` |

### going forward

I'll be updating the repo soon with my local WIP source. From there I'll be working on reaching feature parity as closely as possible ( or as much as makes sense ) to v0.10.0 before adding additional features. I welcome any feedback on these proposed changes and of course any contributions that help push trilogy toward them. Thanks all!

**Update 1-5-17**: the [next branch](https://github.com/citycide/trilogy/tree/next) has been pushed with the WIP source.

### todo

- [x] Update tests, which means pretty much a complete overhaul since the entire API has changed
- [x] Write new docs which, again, means an overhaul ( **update 1-6-17**: [see WIP here](https://github.com/citycide/trilogy/blob/next/docs/api.md) )
- [x] Publish to npm under the `@next` tag
- [x] Review feature parity situation with v0.10.0
